---
apiVersion: v1
name: post
version: 1.1.1
description: OTUS reddit application POST homework
home: https://github.com/czm41k/helm-charts/
maintainers:
  - name: czm41k
    email: etselikov@express42.com
appVersion: 1.0
...
